export const GET_MOVIE_DATA = "GET_MOVIE_DATA";
export const GET_DISCOVER_MOVIE_DATA = "GET_DISCOVER_MOVIE_DATA";
export const GET_POPULAR_MOVIE_DATA = "GET_POPULAR_MOVIE_DATA";
export const GET_TOP_RATED_MOVIE_DATA = "GET_TOP_RATED_MOVIE_DATA";
